
server
{
    listen 8080;
    server_name localhost;

    root ./www;
    index index.html index.htm;

    client_max_body_size 10M;

    error_page 404 ./errors/404.html;
    error_page 403 ./errors/403.html;
    error_page 500 ./errors/500.html;

    location /
    {
        allowed_methods GET POST;
    }

    location /images
    {
        root ./assets/images;
        allowed_methods GET;
        autoindex off;
    }

    location /downloads
    {
        root ./downloads;
        allowed_methods GET;
        autoindex on;
    }

    location /upload
    {
        root ./uploads;
        allowed_methods POST DELETE;
    }

    location /cgi-bin
    {
        allowed_methods GET POST;

        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }
}